apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: anchorpeer-allchannel-mh
  namespace: mh-net
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: anchorpeer-allchannel-mh
  chart:
    git: git@github.com:himanshulalarya/blockchain-automation-framework.git
    ref: fabric
    path: platforms/hyperledger-fabric/charts/anchorpeer
  values:
    metadata:
      namespace: mh-net
      images:
        fabrictools: hyperledger/fabric-tools:2.0.0
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    peer:
      name: peer0
      address: peer0.mh-net.hf.dev.aws.blockchaincloudpoc-develop.com:8443
      localmspid: mhMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://vault.internal.dev.aws.blockchaincloudpoc-develop.com:8200
      authpath: mh-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/mh-net/users/admin
      orderersecretprefix: secret/crypto/peerOrganizations/mh-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: allchannel      
    orderer:
      address: orderer3.hf.dev.aws.blockchaincloudpoc-develop.com:8443
    anchorstx: |-
      CtMCChgKFggCGgYI3YnE+QUiCmFsbGNoYW5uZWwStgIKswIKCmFsbGNoYW5uZWwSXhJcCgtBcHBs
      aWNhdGlvbhJNCAESSQoFbWhNU1ASQBoHCgNNU1ASACIKCgZBZG1pbnMSACIPCgtFbmRvcnNlbWVu
      dBIAIgsKB1JlYWRlcnMSACILCgdXcml0ZXJzEgAaxAESwQEKC0FwcGxpY2F0aW9uErEBCAESrAEK
      BW1oTVNQEqIBCAEaVgoLQW5jaG9yUGVlcnMSRxI9CjsKNnBlZXIwLm1oLW5ldC5oZi5kZXYuYXdz
      LmJsb2NrY2hhaW5jbG91ZHBvYy1kZXZlbG9wLmNvbRD7QRoGQWRtaW5zGgcKA01TUBIAIgsKB1dy
      aXRlcnMSACIKCgZBZG1pbnMSACIPCgtFbmRvcnNlbWVudBIAIgsKB1JlYWRlcnMSACoGQWRtaW5z

