apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: approve-mh-allchannel-supplychain1
  namespace: mh-net
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: approve-mh-allchannel-supplychain1
  chart:
    git: git@github.com:himanshulalarya/blockchain-automation-framework.git
    ref: fabric2.2v
    path: platforms/hyperledger-fabric/charts/approve_chaincode
  values:
    metadata:
      namespace: mh-net
      images:
        fabrictools: hyperledger/fabric-tools:2.2.0
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    peer:
      name: peer0
      address: peer0.mh-net:7051
      localmspid: mhMSP
      loglevel: debug
      tlsstatus: true
    vault:
      role: vault-role
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      authpath: mh-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/mh-net/users/admin 
      orderersecretprefix: secret/crypto/peerOrganizations/mh-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred
      tls: false
    orderer:
      address: orderer3.hf.dev2.aws.blockchaincloudpoc-develop.com:8443
    chaincode:
      builder: hyperledger/fabric-ccenv:2.2.0
      name: supplychain
      version: 1
      commitarguments: '\"init\",\"\"'
      endorsementpolicies:  ''
    channel:
      name: allchannel
