apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: channel-ch
  namespace: ch-net
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: channel-ch
  chart:
    git: git@github.com:himanshulalarya/blockchain-automation-framework.git
    ref: fabric
    path: platforms/hyperledger-fabric/charts/create_channel   
  values:
    metadata:
      namespace: ch-net
      images:
        fabrictools: hyperledger/fabric-tools:2.0.0
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    peer:
      name: peer0
      address: peer0.ch-net:7051
      localmspid: chMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://vault.internal.dev.aws.blockchaincloudpoc-develop.com:8200
      authpath: ch-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/ch-net/users/admin
      orderersecretprefix: secret/crypto/peerOrganizations/ch-net/orderer 
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: allchannel
    orderer:
      address: orderer3.hf.dev.aws.blockchaincloudpoc-develop.com:8443
    channeltx: |-
      Cr0DChgKFggCGgYI3InE+QUiCmFsbGNoYW5uZWwSoAMKnQMKCmFsbGNoYW5uZWwSNxIlCgtBcHBs
      aWNhdGlvbhIWEgkKBWNoTVNQEgASCQoFbWhNU1ASABoOCgpDb25zb3J0aXVtEgAa1QISqQIKC0Fw
      cGxpY2F0aW9uEpkCCAESCQoFY2hNU1ASABIJCgVtaE1TUBIAGiYKDENhcGFiaWxpdGllcxIWEgwK
      CgoGVjFfNF8yEgAaBkFkbWlucyI1ChRMaWZlY3ljbGVFbmRvcnNlbWVudBIdEhMIAxIPCgtFbmRv
      cnNlbWVudBACGgZBZG1pbnMiLAoLRW5kb3JzZW1lbnQSHRITCAMSDwoLRW5kb3JzZW1lbnQQAhoG
      QWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zIiIKB1dyaXRlcnMSFxIN
      CAMSCQoHV3JpdGVycxoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5z
      KgZBZG1pbnMaJwoKQ29uc29ydGl1bRIZEhcKFVN1cHBseUNoYWluQ29uc29ydGl1bQ==