apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: anchorpeer-allchannel-ch
  namespace: ch-net
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: anchorpeer-allchannel-ch
  chart:
    git: git@github.com:himanshulalarya/blockchain-automation-framework.git
    ref: new
    path: platforms/hyperledger-fabric/charts/anchorpeer
  values:
    metadata:
      namespace: ch-net
      images:
        fabrictools: hyperledger/fabric-tools:2.0.0
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    peer:
      name: peer0
      address: peer0.ch-net.hf.dev.aws.blockchaincloudpoc-develop.com:8443
      localmspid: chMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      authpath: ch-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/ch-net/users/admin
      orderersecretprefix: secret/crypto/peerOrganizations/ch-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: allchannel      
    orderer:
      address: orderer3.hf.dev.aws.blockchaincloudpoc-develop.com:8443
    anchorstx: |-
      CtMCChgKFggCGgYIpKX6+QUiCmFsbGNoYW5uZWwStgIKswIKCmFsbGNoYW5uZWwSXhJcCgtBcHBs
      aWNhdGlvbhJNCAESSQoFY2hNU1ASQBoHCgNNU1ASACILCgdSZWFkZXJzEgAiCwoHV3JpdGVycxIA
      IgoKBkFkbWlucxIAIg8KC0VuZG9yc2VtZW50EgAaxAESwQEKC0FwcGxpY2F0aW9uErEBCAESrAEK
      BWNoTVNQEqIBCAEaVgoLQW5jaG9yUGVlcnMSRxI9CjsKNnBlZXIwLmNoLW5ldC5oZi5kZXYuYXdz
      LmJsb2NrY2hhaW5jbG91ZHBvYy1kZXZlbG9wLmNvbRD7QRoGQWRtaW5zGgcKA01TUBIAIgoKBkFk
      bWlucxIAIg8KC0VuZG9yc2VtZW50EgAiCwoHUmVhZGVycxIAIgsKB1dyaXRlcnMSACoGQWRtaW5z

