apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: anchorpeer-allchannel-ch
  namespace: ch-net
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: anchorpeer-allchannel-ch
  chart:
    git: git@github.com:himanshulalarya/blockchain-automation-framework.git
    ref: fabric2.2v
    path: platforms/hyperledger-fabric/charts/anchorpeer
  values:
    metadata:
      namespace: ch-net
      images:
        fabrictools: hyperledger/fabric-tools:1.4.4
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    peer:
      name: peer0
      address: peer0.ch-net.hf.dev2.aws.blockchaincloudpoc-develop.com:8443
      localmspid: chMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      authpath: ch-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/ch-net/users/admin
      orderersecretprefix: secret/crypto/peerOrganizations/ch-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: allchannel      
    orderer:
      address: orderer8.hf.dev2.aws.blockchaincloudpoc-develop.com:8443
    anchorstx: |-
      CroCChAKDggCIgphbGxjaGFubmVsEqUCCqICCgphbGxjaGFubmVsElUSUwoLQXBwbGljYXRpb24S
      RAgBEjgKBWNoTVNQEi8aBwoDTVNQEgAiCwoHUmVhZGVycxIAIgsKB1dyaXRlcnMSACIKCgZBZG1p
      bnMSACoGQWRtaW5zGrwBErkBCgtBcHBsaWNhdGlvbhKpAQgBEpwBCgVjaE1TUBKSAQgBGgcKA01T
      UBIAGlcKC0FuY2hvclBlZXJzEkgSPgo8CjdwZWVyMC5jaC1uZXQuaGYuZGV2Mi5hd3MuYmxvY2tj
      aGFpbmNsb3VkcG9jLWRldmVsb3AuY29tEPtBGgZBZG1pbnMiCgoGQWRtaW5zEgAiCwoHUmVhZGVy
      cxIAIgsKB1dyaXRlcnMSACoGQWRtaW5zKgZBZG1pbnM=

