apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: commit-ch-allchannel-supplychain1
  namespace: ch-net
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: commit-ch-allchannel-supplychain1
  chart:
    git: git@github.com:himanshulalarya/blockchain-automation-framework.git
    ref: pr-clone
    path: platforms/hyperledger-fabric/charts/commit_chaincode
  values:
    metadata:
      namespace: ch-net
      images:
        fabrictools: hyperledger/fabric-tools:2.2.0
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    peer:
      name: peer0
      address: peer0.ch-net:7051
      localmspid: chMSP
      loglevel: debug
      tlsstatus: true
    vault:
      role: vault-role
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      authpath: ch-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/ch-net/users/admin
      orderersecretprefix: secret/crypto/peerOrganizations/ch-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred
      tls: false
    orderer:
      address: orderer8.hf.dev2.aws.blockchaincloudpoc-develop.com:8443
    chaincode:
      builder: hyperledger/fabric-ccenv:2.2.0
      name: supplychain
      version: 1
      commitarguments: '\"init\",\"\"'
      endorsementpolicies:  ''
    channel:
      name: allchannel
    endorsers:
      creator: ch-net
      name: ch mh  
      corepeeraddress: peer0.ch-net.hf.dev2.aws.blockchaincloudpoc-develop.com:8443 peer0.mh-net.hf.dev2.aws.blockchaincloudpoc-develop.com:8443 
