apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: sh-orderer2
  namespace: sh-net
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: sh-orderer2
  chart:
    git: git@github.com:himanshulalarya/blockchain-automation-framework.git
    ref: fabric-test
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: sh-net
      images:
        orderer: hyperledger/fabric-orderer:1.4.4
        alpineutils: adopblockchaincloud0502.azurecr.io/alpine-utils:1.0

    orderer:
      name: orderer2
      loglevel: info
      localmspid: shMSP
      tlsstatus: true
      keepaliveserverinterval: 10s

    storage:
      storageclassname: shsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://a6167b0bf69b911eab1a00673ff61cbe-206589349.eu-west-1.elb.amazonaws.com:9000
      role: vault-role
      authpath: sh-net-auth
      secretprefix: secret/crypto/ordererOrganizations/sh-net/orderers/orderer2.sh-net
      imagesecretname: regcred
      serviceaccountname: vault-auth
    kafka:
      readinesscheckinterval: 10
      readinessthreshold: 10
      brokers:
      - kafka-0.broker.sh-net.svc.cluster.local:9092
      - kafka-1.broker.sh-net.svc.cluster.local:9092
      - kafka-2.broker.sh-net.svc.cluster.local:9092
      - kafka-3.broker.sh-net.svc.cluster.local:9092

    proxy:
      provider: haproxy
      external_url_suffix: hf.dev.aws.blockchaincloudpoc-develop.com

    genesis: |-
      CiIaIJvmX/kiKev+mOv1/6B57a4ouGot7Z50sEliNzaUTPw4Et1eCtpeCtdeCnkKWwgBEAEaBgjC
      gYb0BSILdGVzdGNoYWluaWQqQGFjM2U5ZmQxYjAyZTkxMGQ2ZTU0NzkwZTBkNzBhMTM1ZTJlMzhi
      YzBjY2Q1ZThiNzUxNWVjMWVkNmI5OWRkMjYSGhIYRdw8r+wGEp6HT1R+VFYUtCv7jEPnuEECEtld
      CtZdEtNdEqwZCgdPcmRlcmVyEqAZEvcUCgVzaE1TUBLtFBrREwoDTVNQEskTEr4TErsTCgVzaE1T
      UBLNBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCNURDQ0FZbWdBd0lCQWdJSkFJZ1Vp
      cFBodnhRYU1Bb0dDQ3FHU000OUJBTUNNRlV4Q3pBSkJnTlZCQVlUCkFrZENNUTh3RFFZRFZRUUlE
      QVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFNQTRHQTFVRUNnd0gKVDNKa1pYSmxj
      akVTTUJBR0ExVUVBd3dKWTJFdWMyZ3RibVYwTUI0WERUSXdNRE16TURBMU1EWTBOMW9YRFRJegpN
      REV4T0RBMU1EWTBOMW93VlRFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHCkExVUVCd3dHVEc5dVpHOXVNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUkl3RUFZRFZR
      UUREQWxqWVM1emFDMXUKWlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFReXds
      QVlVS0hzK1JHa1dHSU5UbW5aS0l1Qgo3Qzd2aTZseWY3V0ZqTlZPbHd5YkRLZU1La3NLYlIvNjNP
      Vmd3aUZWbGkvSTk2Y1NYVDBYUnM0VTJ5TmdvMEl3ClFEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01B
      NEdBMVVkRHdFQi93UUVBd0lCcGpBZEJnTlZIUTRFRmdRVURvYkoKckdrRlh5dnk3alczVHlTZXpz
      YlNVOFl3Q2dZSUtvWkl6ajBFQXdJRFNRQXdSZ0loQU1IT3BMZ3FjWWgxUS81aQoxV2UrdlFmc1ZR
      c05DWUpaaGRFVWladjd5M2ZMQWlFQWdYMXJNMzNyRXB0N1JmQUh0bHgwRzB3Mi9XcXllSkFhCkw1
      cmxSM2p4bVhnPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiKBCC0tLS0tQkVHSU4gQ0VSVElG
      SUNBVEUtLS0tLQpNSUlDeURDQ0FtNmdBd0lCQWdJVUJZOTh0UnF2bU4wdXZoeitmaUdZSVlzY0Ez
      SXdDZ1lJS29aSXpqMEVBd0l3ClZURUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJt
      UnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJJd0VB
      WURWUVFEREFsallTNXphQzF1WlhRd0hoY05NakF3TXpNdwpNRFV4TURBd1doY05NakV3TXpNd01E
      VXhOVEF3V2pCa01Rc3dDUVlEVlFRR0V3SkhRakViTUJrR0ExVUVCeE1TCk5URXVOVEF2TFRBdU1U
      TXZURzl1Wkc5dU1SQXdEZ1lEVlFRS0V3ZFBjbVJsY21WeU1ROHdEUVlEVlFRTEV3WmoKYkdsbGJu
      UXhGVEFUQmdOVkJBTU1ERUZrYldsdVFITm9MVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHU000
      OQpBd0VIQTBJQUJEdWxWWSs2WDNtaStHVlBhbGpHZjhTdkpibTlsVDNVN0Z5TTZ4SVpzN3AyRzU2
      Rkl0azFpY1VGCnd1ak5manVZcjJqTGltdGdvYUhQVkVwMDRIcm1pc1dqZ2dFTE1JSUJCekFPQmdO
      VkhROEJBZjhFQkFNQ0I0QXcKREFZRFZSMFRBUUgvQkFJd0FEQWRCZ05WSFE0RUZnUVVYOUVVaU9L
      RmliODRaTzVYZzRMU1krREQ4Umd3SHdZRApWUjBqQkJnd0ZvQVVEb2JKckdrRlh5dnk3alczVHlT
      ZXpzYlNVOFl3SXdZRFZSMFJCQnd3R29JWVkyRXRkRzl2CmJITXRObVptWmpabU9EWTNMVFZ1WjJz
      eU1JR0JCZ2dxQXdRRkJnY0lBUVIxZXlKaGRIUnljeUk2ZXlKaFltRmoKTG1sdWFYUWlPaUowY25W
      bElpd2lZV1J0YVc0aU9pSjBjblZsSWl3aWFHWXVRV1ptYVd4cFlYUnBiMjRpT2lJaQpMQ0pvWmk1
      RmJuSnZiR3h0Wlc1MFNVUWlPaUpCWkcxcGJrQnphQzF1WlhRaUxDSm9aaTVVZVhCbElqb2lZMnhw
      ClpXNTBJbjE5TUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSVFEZ2F0bk9rdGN6TFYzQ3NPbkhaQmFX
      eFQxazlFVXQKNmFXQ2lkd0RFcE1MSGdJZ1dPaEFtam9UdkNVcm1rZjdGWmI5WGlwR1l5a1R4ZHN6
      VnVKbFB5Z1hBamc9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrN
      BS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCNURDQ0FZbWdBd0lCQWdJSkFJZ1VpcFBo
      dnhRYU1Bb0dDQ3FHU000OUJBTUNNRlV4Q3pBSkJnTlZCQVlUCkFrZENNUTh3RFFZRFZRUUlEQVpN
      YjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFNQTRHQTFVRUNnd0gKVDNKa1pYSmxjakVT
      TUJBR0ExVUVBd3dKWTJFdWMyZ3RibVYwTUI0WERUSXdNRE16TURBMU1EWTBOMW9YRFRJegpNREV4
      T0RBMU1EWTBOMW93VlRFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBN
      QTBHCkExVUVCd3dHVEc5dVpHOXVNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUkl3RUFZRFZRUURE
      QWxqWVM1emFDMXUKWlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFReXdsQVlV
      S0hzK1JHa1dHSU5UbW5aS0l1Qgo3Qzd2aTZseWY3V0ZqTlZPbHd5YkRLZU1La3NLYlIvNjNPVmd3
      aUZWbGkvSTk2Y1NYVDBYUnM0VTJ5TmdvMEl3ClFEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BNEdB
      MVVkRHdFQi93UUVBd0lCcGpBZEJnTlZIUTRFRmdRVURvYkoKckdrRlh5dnk3alczVHlTZXpzYlNV
      OFl3Q2dZSUtvWkl6ajBFQXdJRFNRQXdSZ0loQU1IT3BMZ3FjWWgxUS81aQoxV2UrdlFmc1ZRc05D
      WUpaaGRFVWladjd5M2ZMQWlFQWdYMXJNMzNyRXB0N1JmQUh0bHgwRzB3Mi9XcXllSkFhCkw1cmxS
      M2p4bVhnPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIi4KB1JlYWRlcnMSIxIZ
      CAESFRIIEgYIARICCAAaCRIHCgVzaE1TUBoGQWRtaW5zIi4KB1dyaXRlcnMSIxIZCAESFRIIEgYI
      ARICCAAaCRIHCgVzaE1TUBoGQWRtaW5zIi8KBkFkbWlucxIlEhsIARIXEggSBggBEgIIABoLEgkK
      BXNoTVNQEAEaBkFkbWlucyoGQWRtaW5zGh8KE0NoYW5uZWxSZXN0cmljdGlvbnMSCBoGQWRtaW5z
      GiQKDENhcGFiaWxpdGllcxIUEgoKCAoEVjFfMRIAGgZBZG1pbnMa1AEKDEthZmthQnJva2VycxLD
      ARK4AQosa2Fma2EtMC5icm9rZXIuc2gtbmV0LnN2Yy5jbHVzdGVyLmxvY2FsOjkwOTIKLGthZmth
      LTEuYnJva2VyLnNoLW5ldC5zdmMuY2x1c3Rlci5sb2NhbDo5MDkyCixrYWZrYS0yLmJyb2tlci5z
      aC1uZXQuc3ZjLmNsdXN0ZXIubG9jYWw6OTA5Mgosa2Fma2EtMy5icm9rZXIuc2gtbmV0LnN2Yy5j
      bHVzdGVyLmxvY2FsOjkwOTIaBkFkbWlucxoiCg1Db25zZW5zdXNUeXBlEhESBwoFa2Fma2EaBkFk
      bWlucxoiCglCYXRjaFNpemUSFRILCAoQgICAMRiAgEAaBkFkbWlucxoeCgxCYXRjaFRpbWVvdXQS
      DhIECgIycxoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zIiIKB1Jl
      YWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoHV3JpdGVy
      cxoGQWRtaW5zIioKD0Jsb2NrVmFsaWRhdGlvbhIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMqBkFk
      bWlucxLGQQoLQ29uc29ydGl1bXMStkES60AKFVN1cHBseUNoYWluQ29uc29ydGl1bRLRQBKAIAoF
      Y2hNU1AS9h8a2h4KA01TUBLSHhLHHhLEHgoFY2hNU1ASwAUtLS0tLUJFR0lOIENFUlRJRklDQVRF
      LS0tLS0KTUlJQjJqQ0NBWCtnQXdJQkFnSUpBS3RKVmpYblp0VTNNQW9HQ0NxR1NNNDlCQU1DTUZB
      eEN6QUpCZ05WQkFZVApBa2RDTVE4d0RRWURWUVFJREFaTWIyNWtiMjR4RHpBTkJnTlZCQWNNQmt4
      dmJtUnZiakVMTUFrR0ExVUVDZ3dDClEyZ3hFakFRQmdOVkJBTU1DV05oTG1Ob0xXNWxkREFlRncw
      eU1EQXpNekF3TlRBM01UQmFGdzB5TXpBeE1UZ3cKTlRBM01UQmFNRkF4Q3pBSkJnTlZCQVlUQWtk
      Q01ROHdEUVlEVlFRSURBWk1iMjVrYjI0eER6QU5CZ05WQkFjTQpCa3h2Ym1SdmJqRUxNQWtHQTFV
      RUNnd0NRMmd4RWpBUUJnTlZCQU1NQ1dOaExtTm9MVzVsZERCWk1CTUdCeXFHClNNNDlBZ0VHQ0Nx
      R1NNNDlBd0VIQTBJQUJOcGRzdE43bTd4VFE2Qjd2TmdQNEtnU2xVRkk1bDlXTTJ1dHZHa2gKanlK
      Z1RoTVhVb0xJUDMzKzBHQTZHK3k4OENtN3hCOThKeERKRDZCOXRITE5oekdqUWpCQU1BOEdBMVVk
      RXdFQgovd1FGTUFNQkFmOHdEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUzE0dTM3
      bFpLbXlHcnM0eC95CkFuYjZiOVgvbkRBS0JnZ3Foa2pPUFFRREFnTkpBREJHQWlFQXpoZ3hFL3Vl
      RUVvWlVkT1dQdVpPUWhjR2U2N0gKYTdOMXhQNmg0UzRYMnBnQ0lRRFVIQklQL2JUazZGSWNPWkxO
      Zm5JZ1BIblhUNVY0TXFkM00wODNDQ1NCaEE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiKF
      CC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDeXpDQ0FuR2dBd0lCQWdJVVZBRnJGYWI5
      eHpML2hLTzZMZHhnRnd0T0sxRXdDZ1lJS29aSXpqMEVBd0l3ClVERUxNQWtHQTFVRUJoTUNSMEl4
      RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVFzd0NRWURWUVFL
      REFKRGFERVNNQkFHQTFVRUF3d0pZMkV1WTJndGJtVjBNQjRYRFRJd01ETXpNREExTVRFdwpNRm9Y
      RFRJeE1ETXpNREExTVRZd01Gb3dhakVMTUFrR0ExVUVCaE1DUjBJeEd6QVpCZ05WQkFjVEVqVXhM
      alV3Ckx5MHdMakV6TDB4dmJtUnZiakVMTUFrR0ExVUVDaE1DUTJneEdqQU5CZ05WQkFzVEJtTnNh
      V1Z1ZERBSkJnTlYKQkFzVEFtTm9NUlV3RXdZRFZRUUREQXhCWkcxcGJrQmphQzF1WlhRd1dUQVRC
      Z2NxaGtqT1BRSUJCZ2dxaGtqTwpQUU1CQndOQ0FBUTBNb0haTW9sRVdUczBIcDRmc1VjNzhHM05Z
      MFpzclNMenN5UythNFpiZGpDZ2tZSnBPaUFuClV1QjZLN1NZaktQSWJyY1hTY001QkEvUHFhdnZt
      THUybzRJQkRUQ0NBUWt3RGdZRFZSMFBBUUgvQkFRREFnZUEKTUF3R0ExVWRFd0VCL3dRQ01BQXdI
      UVlEVlIwT0JCWUVGRUZhU3VrMmlnbXJxUmg2UmxTNDB0Z08xRndGTUI4RwpBMVVkSXdRWU1CYUFG
      TFhpN2Z1VmtxYklhdXpqSC9JQ2R2cHYxZitjTUNNR0ExVWRFUVFjTUJxQ0dHTmhMWFJ2CmIyeHpM
      VFptWm1ZMlpqZzJOeTEwWkc1cVpqQ0Jnd1lJS2dNRUJRWUhDQUVFZDNzaVlYUjBjbk1pT25zaVlX
      SmgKWXk1cGJtbDBJam9pZEhKMVpTSXNJbUZrYldsdUlqb2lkSEoxWlNJc0ltaG1Ma0ZtWm1sc2FX
      RjBhVzl1SWpvaQpZMmdpTENKb1ppNUZibkp2Ykd4dFpXNTBTVVFpT2lKQlpHMXBia0JqYUMxdVpY
      UWlMQ0pvWmk1VWVYQmxJam9pClkyeHBaVzUwSW4xOU1Bb0dDQ3FHU000OUJBTUNBMGdBTUVVQ0lR
      Q1Z1K2FubC9kSm1CKyt3UFE2cVo5aWZpcEYKUndkZzM4YURNS0E2bDRITWlnSWdCWUJLalZuWlR1
      SU9ndjc4V2kxNTRFMFZPY0h5eDJJWW16eVVRNUFISDFBPQotLS0tLUVORCBDRVJUSUZJQ0FURS0t
      LS0tCkIOCgRTSEEyEgZTSEEyNTZKwAUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQjJq
      Q0NBWCtnQXdJQkFnSUpBS3RKVmpYblp0VTNNQW9HQ0NxR1NNNDlCQU1DTUZBeEN6QUpCZ05WQkFZ
      VApBa2RDTVE4d0RRWURWUVFJREFaTWIyNWtiMjR4RHpBTkJnTlZCQWNNQmt4dmJtUnZiakVMTUFr
      R0ExVUVDZ3dDClEyZ3hFakFRQmdOVkJBTU1DV05oTG1Ob0xXNWxkREFlRncweU1EQXpNekF3TlRB
      M01UQmFGdzB5TXpBeE1UZ3cKTlRBM01UQmFNRkF4Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlEVlFR
      SURBWk1iMjVrYjI0eER6QU5CZ05WQkFjTQpCa3h2Ym1SdmJqRUxNQWtHQTFVRUNnd0NRMmd4RWpB
      UUJnTlZCQU1NQ1dOaExtTm9MVzVsZERCWk1CTUdCeXFHClNNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJ
      QUJOcGRzdE43bTd4VFE2Qjd2TmdQNEtnU2xVRkk1bDlXTTJ1dHZHa2gKanlKZ1RoTVhVb0xJUDMz
      KzBHQTZHK3k4OENtN3hCOThKeERKRDZCOXRITE5oekdqUWpCQU1BOEdBMVVkRXdFQgovd1FGTUFN
      QkFmOHdEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUzE0dTM3bFpLbXlHcnM0eC95
      CkFuYjZiOVgvbkRBS0JnZ3Foa2pPUFFRREFnTkpBREJHQWlFQXpoZ3hFL3VlRUVvWlVkT1dQdVpP
      UWhjR2U2N0gKYTdOMXhQNmg0UzRYMnBnQ0lRRFVIQklQL2JUazZGSWNPWkxOZm5JZ1BIblhUNVY0
      TXFkM00wODNDQ1NCaEE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tClqcCwgBEssFCsAFLS0t
      LS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIyakNDQVgrZ0F3SUJBZ0lKQUt0SlZqWG5adFUz
      TUFvR0NDcUdTTTQ5QkFNQ01GQXhDekFKQmdOVkJBWVQKQWtkQ01ROHdEUVlEVlFRSURBWk1iMjVr
      YjI0eER6QU5CZ05WQkFjTUJreHZibVJ2YmpFTE1Ba0dBMVVFQ2d3QwpRMmd4RWpBUUJnTlZCQU1N
      Q1dOaExtTm9MVzVsZERBZUZ3MHlNREF6TXpBd05UQTNNVEJhRncweU16QXhNVGd3Ck5UQTNNVEJh
      TUZBeEN6QUpCZ05WQkFZVEFrZENNUTh3RFFZRFZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY00K
      Qmt4dmJtUnZiakVMTUFrR0ExVUVDZ3dDUTJneEVqQVFCZ05WQkFNTUNXTmhMbU5vTFc1bGREQlpN
      Qk1HQnlxRwpTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCTnBkc3RON203eFRRNkI3dk5nUDRLZ1Ns
      VUZJNWw5V00ydXR2R2toCmp5SmdUaE1YVW9MSVAzMyswR0E2Ryt5ODhDbTd4Qjk4SnhESkQ2Qjl0
      SExOaHpHalFqQkFNQThHQTFVZEV3RUIKL3dRRk1BTUJBZjh3RGdZRFZSMFBBUUgvQkFRREFnR21N
      QjBHQTFVZERnUVdCQlMxNHUzN2xaS215R3JzNHgveQpBbmI2YjlYL25EQUtCZ2dxaGtqT1BRUURB
      Z05KQURCR0FpRUF6aGd4RS91ZUVFb1pVZE9XUHVaT1FoY0dlNjdICmE3TjF4UDZoNFM0WDJwZ0NJ
      UURVSEJJUC9iVGs2RkljT1pMTmZuSWdQSG5YVDVWNE1xZDNNMDgzQ0NTQmhBPT0KLS0tLS1FTkQg
      Q0VSVElGSUNBVEUtLS0tLQoSBmNsaWVudBrJBQrABS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0t
      LQpNSUlCMmpDQ0FYK2dBd0lCQWdJSkFLdEpWalhuWnRVM01Bb0dDQ3FHU000OUJBTUNNRkF4Q3pB
      SkJnTlZCQVlUCkFrZENNUTh3RFFZRFZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1S
      dmJqRUxNQWtHQTFVRUNnd0MKUTJneEVqQVFCZ05WQkFNTUNXTmhMbU5vTFc1bGREQWVGdzB5TURB
      ek16QXdOVEEzTVRCYUZ3MHlNekF4TVRndwpOVEEzTVRCYU1GQXhDekFKQmdOVkJBWVRBa2RDTVE4
      d0RRWURWUVFJREFaTWIyNWtiMjR4RHpBTkJnTlZCQWNNCkJreHZibVJ2YmpFTE1Ba0dBMVVFQ2d3
      Q1EyZ3hFakFRQmdOVkJBTU1DV05oTG1Ob0xXNWxkREJaTUJNR0J5cUcKU000OUFnRUdDQ3FHU000
      OUF3RUhBMElBQk5wZHN0TjdtN3hUUTZCN3ZOZ1A0S2dTbFVGSTVsOVdNMnV0dkdraApqeUpnVGhN
      WFVvTElQMzMrMEdBNkcreTg4Q203eEI5OEp4REpENkI5dEhMTmh6R2pRakJBTUE4R0ExVWRFd0VC
      Ci93UUZNQU1CQWY4d0RnWURWUjBQQVFIL0JBUURBZ0dtTUIwR0ExVWREZ1FXQkJTMTR1MzdsWktt
      eUdyczR4L3kKQW5iNmI5WC9uREFLQmdncWhrak9QUVFEQWdOSkFEQkdBaUVBemhneEUvdWVFRW9a
      VWRPV1B1Wk9RaGNHZTY3SAphN04xeFA2aDRTNFgycGdDSVFEVUhCSVAvYlRrNkZJY09aTE5mbkln
      UEhuWFQ1VjRNcWQzTTA4M0NDU0JoQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KEgRwZWVy
      GgZBZG1pbnMiLwoGQWRtaW5zEiUSGwgBEhcSCBIGCAESAggAGgsSCQoFY2hNU1AQARoGQWRtaW5z
      Ii4KB1JlYWRlcnMSIxIZCAESFRIIEgYIARICCAAaCRIHCgVjaE1TUBoGQWRtaW5zIi4KB1dyaXRl
      cnMSIxIZCAESFRIIEgYIARICCAAaCRIHCgVjaE1TUBoGQWRtaW5zKgZBZG1pbnMS8B8KBW1oTVNQ
      EuYfGsoeCgNNU1ASwh4Stx4StB4KBW1oTVNQErwFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
      Ck1JSUIyRENDQVgrZ0F3SUJBZ0lKQVAxcmFBWndMN1JsTUFvR0NDcUdTTTQ5QkFNQ01GQXhDekFK
      QmdOVkJBWVQKQWtOSU1ROHdEUVlEVlFRSURBWmFkWEpwWTJneER6QU5CZ05WQkFjTUJscDFjbWxq
      YURFTE1Ba0dBMVVFQ2d3QwpUV2d4RWpBUUJnTlZCQU1NQ1dOaExtMW9MVzVsZERBZUZ3MHlNREF6
      TXpBd05UQTJOVGhhRncweU16QXhNVGd3Ck5UQTJOVGhhTUZBeEN6QUpCZ05WQkFZVEFrTklNUTh3
      RFFZRFZRUUlEQVphZFhKcFkyZ3hEekFOQmdOVkJBY00KQmxwMWNtbGphREVMTUFrR0ExVUVDZ3dD
      VFdneEVqQVFCZ05WQkFNTUNXTmhMbTFvTFc1bGREQlpNQk1HQnlxRwpTTTQ5QWdFR0NDcUdTTTQ5
      QXdFSEEwSUFCSTVtVFpFRXA4WVVGY2lEQm5FbTQwcVgyakVCTmFTa2tSYVloRmNpCk9uQVF4WXRt
      OXkzNlcwSGZjYXJiOVRKV2JKTnNQR0I2WHNpVmVKak9Gb3hIV1FDalFqQkFNQThHQTFVZEV3RUIK
      L3dRRk1BTUJBZjh3RGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlF6eE4xZGtzUzRJ
      Nm82dVEwUgpES0xWY0JSMkZqQUtCZ2dxaGtqT1BRUURBZ05IQURCRUFpQmVLbGs3M1JUaC8yd1VL
      STlyekc3UlhMendXVEhCCldtZXZob2hyaE8zQTlRSWdiRXcwZjVQZXJIbjB6MEFRcG11akFrYmZS
      VW13MlZVS0p1Mk1nbnQ1MjVnPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiKFCC0tLS0tQkVH
      SU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDeWpDQ0FuQ2dBd0lCQWdJVUtnckhMckZwY0huU1kySWFt
      WEI1THVnb2crMHdDZ1lJS29aSXpqMEVBd0l3ClVERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZC
      QWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVFzd0NRWURWUVFLREFKTmFERVNN
      QkFHQTFVRUF3d0pZMkV1YldndGJtVjBNQjRYRFRJd01ETXpNREExTVRFdwpNRm9YRFRJeE1ETXpN
      REExTVRZd01Gb3dhVEVMTUFrR0ExVUVCaE1DUTBneEdqQVlCZ05WQkFjVEVUUTNMak00Ckx6Z3VO
      VFF2V25WeWFXTm9NUXN3Q1FZRFZRUUtFd0pOYURFYU1BMEdBMVVFQ3hNR1kyeHBaVzUwTUFrR0Ex
      VUUKQ3hNQ2JXZ3hGVEFUQmdOVkJBTU1ERUZrYldsdVFHMW9MVzVsZERCWk1CTUdCeXFHU000OUFn
      RUdDQ3FHU000OQpBd0VIQTBJQUJLSnFzK253NTdyMk8wdHFTM3hRZ2k3bUd1dXVLbDRjSEFxQ1k0
      RlZFN1JqZHVnMXJGditwUVArCnltSlZGRFJIZFRvSUdTWGFrcHl6K3RHdmh3ejhNYTJqZ2dFTk1J
      SUJDVEFPQmdOVkhROEJBZjhFQkFNQ0I0QXcKREFZRFZSMFRBUUgvQkFJd0FEQWRCZ05WSFE0RUZn
      UVVXZHhkdTc5SDE2NmFPRUk2RXZBejdsQzVUZ3N3SHdZRApWUjBqQkJnd0ZvQVVNOFRkWFpMRXVD
      T3FPcmtORVF5aTFYQVVkaFl3SXdZRFZSMFJCQnd3R29JWVkyRXRkRzl2CmJITXRObVptWmpabU9E
      WTNMWHBqYkRKM01JR0RCZ2dxQXdRRkJnY0lBUVIzZXlKaGRIUnljeUk2ZXlKaFltRmoKTG1sdWFY
      UWlPaUowY25WbElpd2lZV1J0YVc0aU9pSjBjblZsSWl3aWFHWXVRV1ptYVd4cFlYUnBiMjRpT2lK
      dAphQ0lzSW1obUxrVnVjbTlzYkcxbGJuUkpSQ0k2SWtGa2JXbHVRRzFvTFc1bGRDSXNJbWhtTGxS
      NWNHVWlPaUpqCmJHbGxiblFpZlgwd0NnWUlLb1pJemowRUF3SURTQUF3UlFJaEFKZWN2ZjE4L3dM
      L3Y3VG1hWTdKd005SXd0bUYKZDlrbUdUNitvS0FlcjV6ZUFpQWFiRlVqQmtKVXBjMnJ5ZDJXcUdM
      b0Rob3VNSXFVeWdZd1JJOE01VytNMFE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCkIOCgRT
      SEEyEgZTSEEyNTZKvAUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQjJEQ0NBWCtnQXdJ
      QkFnSUpBUDFyYUFad0w3UmxNQW9HQ0NxR1NNNDlCQU1DTUZBeEN6QUpCZ05WQkFZVApBa05JTVE4
      d0RRWURWUVFJREFaYWRYSnBZMmd4RHpBTkJnTlZCQWNNQmxwMWNtbGphREVMTUFrR0ExVUVDZ3dD
      ClRXZ3hFakFRQmdOVkJBTU1DV05oTG0xb0xXNWxkREFlRncweU1EQXpNekF3TlRBMk5UaGFGdzB5
      TXpBeE1UZ3cKTlRBMk5UaGFNRkF4Q3pBSkJnTlZCQVlUQWtOSU1ROHdEUVlEVlFRSURBWmFkWEpw
      WTJneER6QU5CZ05WQkFjTQpCbHAxY21samFERUxNQWtHQTFVRUNnd0NUV2d4RWpBUUJnTlZCQU1N
      Q1dOaExtMW9MVzVsZERCWk1CTUdCeXFHClNNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJJNW1UWkVF
      cDhZVUZjaURCbkVtNDBxWDJqRUJOYVNra1JhWWhGY2kKT25BUXhZdG05eTM2VzBIZmNhcmI5VEpX
      YkpOc1BHQjZYc2lWZUpqT0ZveEhXUUNqUWpCQU1BOEdBMVVkRXdFQgovd1FGTUFNQkFmOHdEZ1lE
      VlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUXp4TjFka3NTNEk2bzZ1UTBSCkRLTFZjQlIy
      RmpBS0JnZ3Foa2pPUFFRREFnTkhBREJFQWlCZUtsazczUlRoLzJ3VUtJOXJ6RzdSWEx6d1dUSEIK
      V21ldmhvaHJoTzNBOVFJZ2JFdzBmNVBlckhuMHowQVFwbXVqQWtiZlJVbXcyVlVLSnUyTWdudDUy
      NWc9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KWpQLCAESxwUKvAUtLS0tLUJFR0lOIENFUlRJ
      RklDQVRFLS0tLS0KTUlJQjJEQ0NBWCtnQXdJQkFnSUpBUDFyYUFad0w3UmxNQW9HQ0NxR1NNNDlC
      QU1DTUZBeEN6QUpCZ05WQkFZVApBa05JTVE4d0RRWURWUVFJREFaYWRYSnBZMmd4RHpBTkJnTlZC
      QWNNQmxwMWNtbGphREVMTUFrR0ExVUVDZ3dDClRXZ3hFakFRQmdOVkJBTU1DV05oTG0xb0xXNWxk
      REFlRncweU1EQXpNekF3TlRBMk5UaGFGdzB5TXpBeE1UZ3cKTlRBMk5UaGFNRkF4Q3pBSkJnTlZC
      QVlUQWtOSU1ROHdEUVlEVlFRSURBWmFkWEpwWTJneER6QU5CZ05WQkFjTQpCbHAxY21samFERUxN
      QWtHQTFVRUNnd0NUV2d4RWpBUUJnTlZCQU1NQ1dOaExtMW9MVzVsZERCWk1CTUdCeXFHClNNNDlB
      Z0VHQ0NxR1NNNDlBd0VIQTBJQUJJNW1UWkVFcDhZVUZjaURCbkVtNDBxWDJqRUJOYVNra1JhWWhG
      Y2kKT25BUXhZdG05eTM2VzBIZmNhcmI5VEpXYkpOc1BHQjZYc2lWZUpqT0ZveEhXUUNqUWpCQU1B
      OEdBMVVkRXdFQgovd1FGTUFNQkFmOHdEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JC
      UXp4TjFka3NTNEk2bzZ1UTBSCkRLTFZjQlIyRmpBS0JnZ3Foa2pPUFFRREFnTkhBREJFQWlCZUts
      azczUlRoLzJ3VUtJOXJ6RzdSWEx6d1dUSEIKV21ldmhvaHJoTzNBOVFJZ2JFdzBmNVBlckhuMHow
      QVFwbXVqQWtiZlJVbXcyVlVLSnUyTWdudDUyNWc9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      EgZjbGllbnQaxQUKvAUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQjJEQ0NBWCtnQXdJ
      QkFnSUpBUDFyYUFad0w3UmxNQW9HQ0NxR1NNNDlCQU1DTUZBeEN6QUpCZ05WQkFZVApBa05JTVE4
      d0RRWURWUVFJREFaYWRYSnBZMmd4RHpBTkJnTlZCQWNNQmxwMWNtbGphREVMTUFrR0ExVUVDZ3dD
      ClRXZ3hFakFRQmdOVkJBTU1DV05oTG0xb0xXNWxkREFlRncweU1EQXpNekF3TlRBMk5UaGFGdzB5
      TXpBeE1UZ3cKTlRBMk5UaGFNRkF4Q3pBSkJnTlZCQVlUQWtOSU1ROHdEUVlEVlFRSURBWmFkWEpw
      WTJneER6QU5CZ05WQkFjTQpCbHAxY21samFERUxNQWtHQTFVRUNnd0NUV2d4RWpBUUJnTlZCQU1N
      Q1dOaExtMW9MVzVsZERCWk1CTUdCeXFHClNNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJJNW1UWkVF
      cDhZVUZjaURCbkVtNDBxWDJqRUJOYVNra1JhWWhGY2kKT25BUXhZdG05eTM2VzBIZmNhcmI5VEpX
      YkpOc1BHQjZYc2lWZUpqT0ZveEhXUUNqUWpCQU1BOEdBMVVkRXdFQgovd1FGTUFNQkFmOHdEZ1lE
      VlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUXp4TjFka3NTNEk2bzZ1UTBSCkRLTFZjQlIy
      RmpBS0JnZ3Foa2pPUFFRREFnTkhBREJFQWlCZUtsazczUlRoLzJ3VUtJOXJ6RzdSWEx6d1dUSEIK
      V21ldmhvaHJoTzNBOVFJZ2JFdzBmNVBlckhuMHowQVFwbXVqQWtiZlJVbXcyVlVLSnUyTWdudDUy
      NWc9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KEgRwZWVyGgZBZG1pbnMiLwoGQWRtaW5zEiUS
      GwgBEhcSCBIGCAESAggAGgsSCQoFbWhNU1AQARoGQWRtaW5zIi4KB1JlYWRlcnMSIxIZCAESFRII
      EgYIARICCAAaCRIHCgVtaE1TUBoGQWRtaW5zIi4KB1dyaXRlcnMSIxIZCAESFRIIEgYIARICCAAa
      CRIHCgVtaE1TUBoGQWRtaW5zKgZBZG1pbnMaQAoVQ2hhbm5lbENyZWF0aW9uUG9saWN5EicSDAgD
      EggKBkFkbWlucxoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMqFy9DaGFubmVsL09yZGVyZXIvQWRt
      aW5zIi0KBkFkbWlucxIjEggIARIEEgISABoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMqFy9DaGFu
      bmVsL09yZGVyZXIvQWRtaW5zGiQKDENhcGFiaWxpdGllcxIUEgoKCAoEVjFfMRIAGgZBZG1pbnMa
      JgoQSGFzaGluZ0FsZ29yaXRobRISEggKBlNIQTI1NhoGQWRtaW5zGi0KGUJsb2NrRGF0YUhhc2hp
      bmdTdHJ1Y3R1cmUSEBIGCP////8PGgZBZG1pbnMaaAoQT3JkZXJlckFkZHJlc3NlcxJUEjkKN29y
      ZGVyZXIyLmhmLmRldi5hd3MuYmxvY2tjaGFpbmNsb3VkcG9jLWRldmVsb3AuY29tOjg0NDMaFy9D
      aGFubmVsL09yZGVyZXIvQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5z
      IiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoH
      V3JpdGVycxoGQWRtaW5zKgZBZG1pbnMaCgoACgAKAAoACgA=
