apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: zkkafka-sh-orderer
  namespace: sh-net
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: zkkafka-sh-orderer
  chart:
    git: git@github.com:himanshulalarya/blockchain-automation-framework.git
    ref: fabric-test
    path: platforms/hyperledger-fabric/charts/zkkafka    
  values:
    metadata: 
      namespace: sh-net
      images:
        kafka: hyperledger/fabric-kafka:0.4.18
        zookeeper: hyperledger/fabric-zookeeper:0.4.18
      
    storage: 
      storageclassname: shsc
      storagesize: 512Mi
    kafka: 
      brokerservicename: broker
      name: kafka
      replicas: 4    
    zookeeper: 
      name: zookeeper
      peerservicename: zoo
      readinesscheckinterval: 10
      readinessthreshold: 10
      replicas: 3