apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: manufacturermanufacturertessera
  namespace: manufacturer-ns
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: manufacturermanufacturertessera
  chart:
    git: git@github.com:himanshulalarya/blockchain-automation-framework.git
    ref: quorum
    path: platforms/quorum/charts/node_tessera  
  values:
    replicaCount: 1
    metadata:
      namespace: manufacturer-ns
      labels:
    images:
      node: quorumengineering/quorum:2.1.1
      alpineutils: adopblockchaincloud0502.azurecr.io/alpine-utils:1.0
      tessera: quorumengineering/tessera:0.9.2
      busybox: busybox
      mysql: mysql/mysql-server:5.7
    node:
      name: manufacturer
      status: default
      consensus: ibft
      subject: O=Manufacturer,OU=Manufacturer,L=47.38/8.54/Zurich,C=CH
      mountPath: /etc/quorum/qdata
      imagePullSecret: regcred
      keystore: keystore_1
      servicetype: ClusterIP
      ports:
        rpc: 8546
        raft: 50401
        tm: 9001
        quorum: 21000
        db: 3306
      dbname: demodb
      mysqluser: demouser
    vault:
      address: http://a4ac3be3a83b211eab1a00673ff61cbe-1097457528.eu-west-1.elb.amazonaws.com:9000
      secretprefix: secret/manufacturer-ns/crypto/manufacturer
      serviceaccountname: vault-auth
      keyname: quorum
      tm_keyname: transaction
      role: vault-role
      authpath: quorummanufacturer
    tessera:
      dburl: "jdbc:mysql://manufacturer:3306/demodb"
      dbusername: demouser
      url: "https://manufacturer.rc.dev.aws.blockchaincloudpoc-develop.com:8443"
      othernodes:
        - url: https://carrier.rc.dev.aws.blockchaincloudpoc-develop.com:8443
        - url: https://manufacturer.rc.dev.aws.blockchaincloudpoc-develop.com:8443
        - url: https://store.rc.dev.aws.blockchaincloudpoc-develop.com:8443
        - url: https://warehouse.rc.dev.aws.blockchaincloudpoc-develop.com:8443
      tls: "STRICT"
      trust: "TOFU"
    genesis: ewogICAgImNvbmZpZyI6IHsKICAgICAgICAiY2hhaW5JZCI6IDEwLAogICAgICAgICJob21lc3RlYWRCbG9jayI6IDAsCiAgICAgICAgImVpcDE1MEJsb2NrIjogMCwKICAgICAgICAiZWlwMTUwSGFzaCI6ICIweDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAiLAogICAgICAgICJlaXAxNTVCbG9jayI6IDAsCiAgICAgICAgImVpcDE1OEJsb2NrIjogMCwKICAgICAgICAiYnl6YW50aXVtQmxvY2siOiAxLAogICAgICAgICJjb25zdGFudGlub3BsZUJsb2NrIjogMCwKICAgICAgICAiaXN0YW5idWwiOiB7CiAgICAgICAgICAgICJlcG9jaCI6IDMwMDAwLAogICAgICAgICAgICAicG9saWN5IjogMCwKICAgICAgICAgICAgImNlaWwyTmJ5M0Jsb2NrIjogMAogICAgICAgIH0sCiAgICAgICAgInR4blNpemVMaW1pdCI6IDEyOCwKICAgICAgICAibWF4Q29kZVNpemUiOiAxMjgsCiAgICAgICAgImlzUXVvcnVtIjogdHJ1ZQogICAgfSwKICAgICJub25jZSI6ICIweDAiLAogICAgInRpbWVzdGFtcCI6ICIweDVlOWVjMjMzIiwKICAgICJleHRyYURhdGEiOiAiMHgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwZjg5YWY4NTQ5NDQ5ODJiMzIyYmQ4MDdiZDRkZmY5OWU0NzYyYTMzY2E2MDJmYjllYjQ5NDY2YzhkZWVhMzYwNzY2MzEwNmZlYmNiNmMyMDdiMjIwNDYwZTA4MDk5NDgzZDY3ZmUyMDkxOWUzMDM0MjAxNTEyMGFiNGNjNzBjZjYwNzBiNDk5NGIzNzZjMjZmMTQ1M2I1OGVhOGQxOGM2ZTU3MzRhMTE4YzZiMWI2NmZiODQxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMGMwIiwKICAgICJnYXNMaW1pdCI6ICIweGUwMDAwMDAwIiwKICAgICJkaWZmaWN1bHR5IjogIjB4MSIsCiAgICAibWl4SGFzaCI6ICIweDYzNzQ2OTYzNjE2YzIwNjI3OTdhNjE2ZTc0Njk2ZTY1MjA2NjYxNzU2Yzc0MjA3NDZmNmM2NTcyNjE2ZTYzNjUiLAogICAgImNvaW5iYXNlIjogIjB4MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMCIsCiAgICAiYWxsb2MiOiB7CiAgICAgICAgIjQ5ODJiMzIyYmQ4MDdiZDRkZmY5OWU0NzYyYTMzY2E2MDJmYjllYjQiOiB7CiAgICAgICAgICAgICJiYWxhbmNlIjogIjB4NDQ2YzNiMTVmOTkyNjY4N2QyYzQwNTM0ZmRiNTY0MDAwMDAwMDAwMDAwIgogICAgICAgIH0sCiAgICAgICAgIjY2YzhkZWVhMzYwNzY2MzEwNmZlYmNiNmMyMDdiMjIwNDYwZTA4MDkiOiB7CiAgICAgICAgICAgICJiYWxhbmNlIjogIjB4NDQ2YzNiMTVmOTkyNjY4N2QyYzQwNTM0ZmRiNTY0MDAwMDAwMDAwMDAwIgogICAgICAgIH0sCiAgICAgICAgIjgzZDY3ZmUyMDkxOWUzMDM0MjAxNTEyMGFiNGNjNzBjZjYwNzBiNDkiOiB7CiAgICAgICAgICAgICJiYWxhbmNlIjogIjB4NDQ2YzNiMTVmOTkyNjY4N2QyYzQwNTM0ZmRiNTY0MDAwMDAwMDAwMDAwIgogICAgICAgIH0sCiAgICAgICAgImIzNzZjMjZmMTQ1M2I1OGVhOGQxOGM2ZTU3MzRhMTE4YzZiMWI2NmYiOiB7CiAgICAgICAgICAgICJiYWxhbmNlIjogIjB4NDQ2YzNiMTVmOTkyNjY4N2QyYzQwNTM0ZmRiNTY0MDAwMDAwMDAwMDAwIgogICAgICAgIH0KICAgIH0sCiAgICAibnVtYmVyIjogIjB4MCIsCiAgICAiZ2FzVXNlZCI6ICIweDAiLAogICAgInBhcmVudEhhc2giOiAiMHgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwIgp9
    staticnodes:
      - enode://d19d4658129fd9e74c6ebe519dff4e26d12670e41c52a4d030ba6e0ef33b03d059dc1ef86037a9cfd3e271bcbf6e85cf7f49bf2994edab35f60e0827d4126fb4@carrier.rc.dev.aws.blockchaincloudpoc-develop.com:15010?discport=0
      - enode://2bfb973d8fc5397323838c25ce416746f5b778f1a811f63b85ec8baaa423c104a38cbcefcb5c6fc144123497e6ced34320da5cfd82aec56e2af3a90c345b1ec6@manufacturer.rc.dev.aws.blockchaincloudpoc-develop.com:15020?discport=0
      - enode://d14686519733370878ed6803e0945e6fe3a927981024a8940bad26d610a6fac61fa03b7d569e3ef8530dc4cba3aabaca91d41fc457b7228bb038066992f41e70@store.rc.dev.aws.blockchaincloudpoc-develop.com:15030?discport=0
      - enode://d55f5810f78dccca481e46f305c8953d4f141182f00ce4d460d30b02daa228eff2ebfe200b68ad9aded752b5ee4617bb614ed4332951793b2615998c12c7f784@warehouse.rc.dev.aws.blockchaincloudpoc-develop.com:15040?discport=0
    proxy:
      provider: "ambassador"
      external_url: manufacturer.rc.dev.aws.blockchaincloudpoc-develop.com
      portTM: 8443
      rpcport: 15021
      quorumport: 15020
    storage:
      storageclassname: awsstorageclass
      storagesize: 1Gi
      dbstorage: 1Gi
