#########################
# Playbook to create deployment files for namespaces, service account and clusterrolebinding
# Playbook arguments: complete network.yaml
#########################
- hosts: ansible_provisioners
  gather_facts: no
  tasks:    
  # Delete build directory
  - name: Remove build directory
    file:
      path: "./build"
      state: absent

  # ----------------------------------------------------------------------
  # # create namespace, service account and clusterrolebinding
  # - name: "Create namespace and service account"
  #   include_role: 
  #     name: create/namespace_serviceaccount
  #   vars:
  #     component_ns: "{{ item.name | lower }}-ent"
  #     organisation: "{{ item.name | lower }}"
  #     kubernetes: "{{ item.k8s }}"
  #     gitops: "{{ item.gitops }}"
  #   loop: "{{ network['organizations'] }}"

  # Create Storageclass
  - name: Create Storage Class
    include_role:
      name: create/storageclass
    vars:
      storageclass_name: "{{ item.cloud_provider }}storageclass"
      git_dir: "{{ item.gitops.release_dir }}"
      org: "{{ item }}"
      kubernetes: "{{ item.k8s }}"
    loop: "{{ network['organizations'] }}"
  
  # Setup Vault-Kubernetes accesses and Regcred for docker registry
  - name: "Setup vault"   
    include_role: 
      name: "setup/vault_kubernetes"
    vars:
      component_ns: "{{ item.name | lower }}-ent"
      kubernetes: "{{ item.k8s }}"
      vault: "{{ item.vault }}"
      component_name: "{{ item.name | lower}}"
      component_path: "{{ item.name | lower }}/"
      component_auth: "cordaent{{ item.name | lower }}"
      component_type: "organization"
    loop: "{{ network['organizations'] }}"

  # ----------------------------------------------------------------------  