apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: ch-cli
  namespace: ch-net
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: ch-cli
  chart:
    git: git@github.com:himanshulalarya/blockchain-automation-framework.git
    ref: new
    path: platforms/hyperledger-fabric/charts/fabric_cli    
  values:
    metadata:
      namespace: ch-net
      images:
        fabrictools: hyperledger/fabric-tools:1.4.4
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    storage:
      class: chsc
      size: 256Mi
    vault:
      role: vault-role
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      authpath: ch-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/ch-net/users/admin
      orderersecretprefix: secret/crypto/peerOrganizations/ch-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred
      tls: false
    peer:
      name: peer0
      localmspid: chMSP
      tlsstatus: true
      address: peer0.ch-net.hf.dev.aws.blockchaincloudpoc-develop.com:8443
    orderer:
      address: orderer3.hf.dev.aws.blockchaincloudpoc-develop.com:8443
